CREATE DATABASE `bookstore`;
USE `bookstore`;

CREATE TABLE categories (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	parent_id INT UNSIGNED,
	FOREIGN KEY (parent_id) REFERENCES categories (id),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE books (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	category_id INT UNSIGNED,
	price DECIMAL (10, 2) UNSIGNED NOT NULL,
	stock_quantity INT NOT NULL DEFAULT 0,
	author_id INT UNSIGNED,
	isbn VARCHAR(50) NOT NULL unique,
	image_url VARCHAR(2083),
    publish_date DATETIME,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	FOREIGN KEY (category_id) REFERENCES categories (id)
);

CREATE TABLE authors (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	email VARCHAR(100) unique NOT NULL,
	phone CHAR(15),
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE customers (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	email VARCHAR(100) unique NOT NULL,
	phone CHAR(15),
	password CHAR(32),
    shipping_address VARCHAR(255) NOT NULL,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE orders (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	customer_id INT UNSIGNED NOT NULL,
	date DATETIME DEFAULT CURRENT_TIMESTAMP,
	total_amount DECIMAL (10, 2) NOT NULL,
    payment_method TINYINT UNSIGNED NOT NULL,
    payment_status TINYINT UNSIGNED DEFAULT 0,
    order_status ENUM('pending','confirmed','processing','shipment','delivered') NOT NULL,
    delivery_date DATETIME NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	FOREIGN KEY (customer_id) REFERENCES customers (id)
);




CREATE TABLE order_details (
    id INT UNSIGNED AUTO_INCREMENT,
	order_id INT UNSIGNED NOT NULL,
	book_id INT UNSIGNED NOT NULL,
	quantity INT NOT NULL,
	price DECIMAL (10, 2) UNSIGNED NOT NULL,
    total_price DECIMAL (10, 2) UNSIGNED NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id,order_id, book_id),
	FOREIGN KEY (order_id) REFERENCES orders (id),
	FOREIGN KEY (book_id) REFERENCES books (id)
);